apps/travel_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^travels$', views.success, name="success"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^home$', views.home, name="home"),
    url(r'^travels/add$', views.create, name="create"),
    url(r'^add_trip$', views.add_trip , name="add_trip"),
    url(r'^travels/destination/(?P<id>\d+)$', views.trip_detail, name = "item_detail"),
    url(r'^move_up/(?P<id>\d+)$', views.move_up, name = "move_up"),
]

exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.user_app.urls', namespace = "users")),
    url(r'^', include('apps.travel_app.urls', namespace = "travel")),
]

apps/travel_app/models.py
from django.db import models
from ..user_app.models import User
from datetime import date




class TravelManager(models.Manager):
    def add_trip(self, trips, userID):
        response={}
        errors=[]
        if Travel.objects.filter(destination  = trips['destination']):
            errors.append("Sorry that destination already exists please add from other user's table")
        if trips['destination'] =="" or  trips['description']=="" or trips['travel_date_from'] =="" or trips['travel_date_to'] =="" :
            errors.append("One or the more fields are empty! All fields should be filled out!")
        if trips['travel_date_from'] <= str(date.today()):
            errors.append("Travel date cannot be from past")
        if trips['travel_date_from'] > trips['travel_date_to']:
            errors.append(" 'Travel Date To' should not be before the 'Travel Date From'!")
        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status']=True
            response['travels'] = Travel.objects.create(destination=trips['destination'], my_plan=User.objects.get(id = userID), description = trips['description'], start_date = trips['travel_date_from'], end_date = trips['travel_date_to'])
            response['travels'].your_plan.add(User.objects.get(id = userID))
        return response

    def trip_detail(self, UserID):
        return self.get(id = UserID)


class Travel(models.Model):
    destination= models.CharField(max_length =225)
    my_plan= models.ForeignKey(User, related_name="my")
    your_plan=models.ManyToManyField(User, related_name="yours")
    description = models.CharField(max_length=255)
    start_date = models.DateField(auto_now=False, auto_now_add=False)
    end_date = models.DateField(auto_now=False, auto_now_add=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    objects = TravelManager()

apps/travel_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Travel
from ..user_app.models import User
from django.contrib import messages

def add_trip(request):
    if request.method == "POST":
        userID = request.session['id']
        trips= {
            "destination" : request.POST["destination"],
            "description" : request.POST["description"],
            "travel_date_from":request.POST['travel_date_from'],
            "travel_date_to" : request.POST["travel_date_to"],
            }
        response = Travel.objects.add_trip(trips, userID)
        print request.POST["destination"]
        print request.POST["travel_date_from"]


        if response['status'] ==False:
            for error in response['errors']:
                messages.add_message(request, messages.ERROR, error)
            return redirect("/travels/add")
        else:
            print "YAYYYYYY"
            messages.add_message(request, messages.SUCCESS, "You have successfully added trip" )
            return redirect("/travels")

    else:
        messages.add_message(request, messages.ERROR, "login/register first")
        return redirect("/main")


def success(request):
    if not 'id' in request.session:
        messages.add_message(request, messages.ERROR, "Please login.")
        return redirect('/main')
    context = {
        'trips': Travel.objects.filter(your_plan = User.objects.get(id = request.session['id'])),
        'all_trips':Travel.objects.exclude(your_plan = User.objects.get(id = request.session['id']))
    }
    return render(request, 'travel_app/index.html', context)

def create(request):
    if not 'id' in request.session:
        messages.add_message(request, messages.ERROR, "Please login.")
        return redirect('/main')
    return render(request, 'travel_app/add.html')

def trip_detail(request, id):
    response = Travel.objects.trip_detail(id)
    context= {
        'trip_detail':response
        }
    return render(request, 'travel_app/detail.html', context)

def move_up(request, id):
    up = Travel.objects.get(id = id)
    person = User.objects.get(id = request.session['id'])
    up.your_plan.add(person)
    return redirect('/travels')


def home(request):
    return redirect("/travels")


def logout(request):
    request.session.clear()
    messages.add_message(request, messages.SUCCESS, "You have logged out!" )
    return redirect("/main")

apps/travel_app/templates/travel_app/add.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Create Item</title>
</head>
<body>
<a href="{%url 'travel:home' %}">Home</a>
<a href="{%url 'travel:logout' %}">Logout</a>
<h1>Add a Trip</h1>
<form action="/add_trip" method="POST">
{% csrf_token %}
<p>Destination: <input type="text" name="destination"></p>
<p>Description: <input type="text" name="description"></p>
<p>Travel Date From:: <input type="Date" name="travel_date_from"></p>
<p>Travel Date To: <input type="Date" name="travel_date_to"></p>
<p></p><input type="submit" name="add" value = "Add"></p>
</form>

{% if messages %}
{% for message in messages %}
  {{ message }}
{% endfor %}
{% endif %}


</body>
</html>

apps/travel_app/templates/travel_app/detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Destination</title>
</head>
<body>

	<a href="{%url 'travel:home' %}">Home</a><br>
	<a href="{%url 'travel:logout' %}">Logout</a>
<h2>{{trip_detail.destination}}</h2>

<p>Planned By:{{trip_detail.my_plan.name}}</p>
<p>Description: {{trip_detail.description}}</p>
<p>Travel Date from: {{trip_detail.start_date}}</p>
<p>Travel Date To: {{trip_detail.end_date}}</p>





	<p>Other Users' joining the trip:</p>
  {% for trip in trip_detail.your_plan.all %}
  <ul>
  <li>{{ trip.name }}</li>
</ul>
  {% endfor %}

</body>
</html>

apps/travel_app/templates/travel_app/index.html
<!DOCTYPE html>
<html>
<head>
<title>Travel</title>
{% load staticfiles %}
<!-- The line above tells Django to be ready to listen for static files -->
<link rel="stylesheet" href="{% static 'travel_app/css/style.css' %}" media="screen" title="no title"  charset="utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>

	<div id="container">
	<h2>Hello, {{request.session.name}}!</h2>
	<a href="{%url 'travel:logout' %}">Logout</a><br>
	<h4>Your Trip Schedules</h4>
	<ul>
	{% if messages %}
	{% for message in messages %}

	<li>{{ message }}</li>
	{% endfor %}
	{% endif %}
	</ul>

<br>

	<table class="table table-bordered">
		<thead>
			<tr>
			<th>Destination</th>
			<th>Travel Start Date</th>
			<th>Travel End date</th>
			<th>Plan</th>
			</tr>
		</thead>


		<tbody>
			{% for trip in trips %}
			<tr>
			<td><a href="{%url 'travel:item_detail' trip.id %}">{{ trip.destination}}</a></td>
			<td>{{trip.start_date}}</td>
			<td>{{trip.end_date}}</td>
			{% if trip.my_plan.id == request.session.id %}
			<td>{{trip.description}}</td>
			{%else%}
			<td>{{trip.description}}</td>


			{% endif %}
			{% endfor %}
			</tr>
		</tbody>
	</table>

	<h4>Other users plan:</h4><br>
	<table class="table table-bordered">
		<thead>
			<tr>
			<th>Name</th>
			<th>Destination</th>
			<th>Travel Start Date</th>
			<th>Travel End Date</th>
			<th> Do You Want To Join? </th>
			</tr>
		</thead>

		<tbody>
			{% for trip in all_trips  %}
			{% if trip.my_plan.id != request.session.id %}
			<tr>
			<td>{{trip.my_plan.name}}</td>
			<td><a href="{%url 'travel:item_detail' trip.id %}">{{trip.destination}}</a></td>
			<td>{{trip.start_date}}</td>
			<td>{{trip.end_date}}</td>
			<td><a href="{%url 'travel:move_up' trip.id  %}">Join</a></td>
			</tr>
			{% endif %}
			{% endfor %}

		</tbody>
	</table><br>



	<a href="{%url 'travel:create' %}">Add Travel Plan</a><br><br>
</body>
</html>